### PR TITLE
Created Skills Card Component

### PR DESCRIPTION
**Pull request by sarthakkundra**
[DeWork ticket](https://app.dework.xyz/developer-dao/frontend-p?taskId=f153e3e7-e3b9-4818-b892-33351a88cdf9)

**DOUBT**
Do we need an onClick event for the whole card? I didn't add it because didn't see a use case for it. If it's needed, let me know I'll add it before the review

### CODE REVIEW

**Comment by e-roy** [comment]
@sarthakkundra please add an export here [https://github.com/Soil-labs/eden-app-2-FrontEnd/blob/main/packages/ui/src/cards/index.ts](https://github.com/Soil-labs/eden-app-2-FrontEnd/blob/main/packages/ui/src/cards/index.ts)

**Comment by e-roy** [comment]
We can do onClick in the parent component of this if needed.  So far that's how the other components have been acting

**Comment by sarthakkundra** [comment]
> We can do onClick in the parent component of this if needed. So far that's how the other components like this have been acting

@e-roy I don't quite get it, can you point me to a piece of code or some other component in the repo that might make it clearer?

**Comment by e-roy** [comment]
> > We can do onClick in the parent component of this if needed. So far that's how the other components like this have been acting
> 
> @e-roy I don't quite get it, can you point me to a piece of code or some other component in the repo that might make it clearer?

Absolutely!  [https://github.com/Soil-labs/eden-app-2-FrontEnd/blob/993fa60b8c4f3877b265aa20269f6e9c8a8c84c4/packages/ui/src/components/CandidateSelectionList/CandidateSelectionList.tsx#L76-L89](https://github.com/Soil-labs/eden-app-2-FrontEnd/blob/993fa60b8c4f3877b265aa20269f6e9c8a8c84c4/packages/ui/src/components/CandidateSelectionList/CandidateSelectionList.tsx#L76-L89)

This is inside of a list component with card children

**Review by e-roy — CHANGES_REQUESTED** [review]
Thank you for updating the other missed exports!

just one change to remove the .vscode/settings.json file [https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request)

**Comment by e-roy** [comment]
@sarthakkundra I had changed the prop on badge from onClick to onClose 

sorry if that's throwing you off

**Comment by sarthakkundra** [comment]
Yeah, no issues, fixing it. Give me a min

**Comment by sarthakkundra** [comment]
@e-roy I think this can be merged now? 👀

**Review by e-roy — APPROVED** [review]

**Pull request merged**
