### PR TITLE
Feat: radial chart

### PR DESCRIPTION
**Pull request by subject026**
Still a WIP but would be good to get some feedback. For instance i'm not sure whether I've installed the libraries in the best place.

### CODE REVIEW

**Comment by e-roy** [comment]
@subject026 first this look really cool!  I know it's a WIP, but I would like to merge it to get it in place on page.

we were having trouble before with build when packages were in the dependencies.  I'm not sure why it was successful for this one, but can you move them to the devDependencies?

you will also need to export this component one level up in the index.ts file, so it can be import from anywhere.

after that I'll merge! :)

**Comment by subject026** [comment]
@e-roy no problem 👍 I'll get that done later today

**Comment by e-roy** [comment]
@subject026 I wanted to check in with you on this.   Are there any blockers?  Is there anything I can help with?

**Comment by subject026** [comment]
@e-roy sorry man totally forgot about this. No worries i'll get these bits done today.

**Review by e-roy — APPROVED** [review]
This is awesome!

**Pull request merged**
