### PR TITLE
Disover page in the alpha app

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
Features Added 

- Discover Page in the Alpha app 
- Working Hours Storybook

### CODE REVIEW

**Comment by e-roy** [comment]
Hi @OleanjiKingCode 

This is looking awesome!   a few things:

- usually when a PR is made the workflow is triggered to run through all the tests, I think the branch conflicts might be stopping that, so if you resolve the conflicts I'm hoping this will run.

- don't worry about the `Vercel - eden-alpha` and `Vercel - eden-foundation` errors, they happen for everyone

- can you move the page `apps/alpha/pages/discover_test/index.tsx` to `apps/alpha/pages/test/discover_test/index.tsx`

- can you create simple render tests for the components you created, this helps catch simple errors for any future changes.  This is more to help optimize for getting to user testing quickly than production level testing.  Don't create a test file for page level.

**Comment by OleanjiKingCode** [comment]
> Hi @OleanjiKingCode
> 
> This is looking awesome! a few things:
> 
> * usually when a PR is made the workflow is triggered to run through all the tests, I think the branch conflicts might be stopping that, so if you resolve the conflicts I'm hoping this will run.
> * don't worry about the `Vercel - eden-alpha` and `Vercel - eden-foundation` errors, they happen for everyone
> * can you move the page `apps/alpha/pages/discover_test/index.tsx` to `apps/alpha/pages/test/discover_test/index.tsx`
> * can you create simple render tests for the components you created, this helps catch simple errors for any future changes.  This is more to help optimize for getting to user testing quickly than production level testing.  Don't create a test file for page level.

Yes i'll start that

**Comment by e-roy** [comment]
Linting errors on the `discover_test` page, just need to remove these if not needed

```
@eden/app-alpha:lint: ./pages/test/discover_test/index.tsx
@eden/app-alpha:lint: 1:1  Error: Run autofix to sort these imports!  simple-import-sort/imports
@eden/app-alpha:lint: 11:3  Error: 'NodesType' is defined but never used.  no-unused-vars
@eden/app-alpha:lint: 22:3  Error: 'RoleList' is defined but never used.  no-unused-vars
@eden/app-alpha:lint: 28:10  Error: 'getFillProfilePercentage' is defined but never used.  no-unused-vars
@eden/app-alpha:lint: 30:8  Error: 'welcome' is defined but never used.  no-unused-vars
@eden/app-alpha:lint: 38:24  Error: 'setSelectedRole' is assigned a value but never used.  no-unused-vars
@eden/app-alpha:lint: 39:11  Error: 'project' is assigned a value but never used.  no-unused-vars
@eden/app-alpha:lint: 39:31  Error: 'setOpenModal' is assigned a value but never used.  no-unused-vars
@eden/app-alpha:lint: 155:10  Error: 'Maybe' is defined but never used.  no-unused-vars
```

**Comment by OleanjiKingCode** [comment]
@e-roy thanks for solving the error,  do you know where the lint error is so I can fix it :)

**Comment by e-roy** [comment]
> @e-roy thanks for solving the error, do you know where the lint error is so I can fix it :)

I think I fixed it manually through github :)  

there is a workflow in the [actions](https://github.com/Soil-labs/eden-app-2-FrontEnd/actions) that displays the error, hopefully you can see it.

I think the rules for `yarn lint` are setup properly to catch the errors locally.  If you try it before the next PR and it doesn't work for you, create an issue :)

thank you!

**Comment by OleanjiKingCode** [comment]
> > @e-roy thanks for solving the error, do you know where the lint error is so I can fix it :)
> 
> I think I fixed it manually through github :)
> 
> there is a workflow in the [actions](https://github.com/Soil-labs/eden-app-2-FrontEnd/actions) that displays the error, hopefully you can see it.
> 
> I think the rules for `yarn lint` are setup properly to catch the errors locally. If you try it before the next PR and it doesn't work for you, create an issue :)
> 
> thank you!

Ohhkay thanks

**Pull request merged**
